### ISSUE TITLE
'docker compose' can't run

### ISSUE THREAD

**Issue by LRW-Adolph** [AirryCo/spt-server-ci#1]
this my docker compose
services:
  spt-server:
    image: dev.sp-tarkov.com/medusa/spt-server:nightly
    container_name: spt-server
    hostname: spt-server
    restart: unless-stopped
    volumes:
      - ./spt-server:/opt/spt-server
    network_mode: host
    environment:
      - backendIp=192.168.8.113
      - backendPort=6969

Bind mount failed: '/volume2/docker/spt/spt-server' does not exist

**Comment by AirryCo** [comment]
Please confirm whether the path `/volume2/docker/spt/spt-server` exists. You can follow the steps below to do so:

```shell
mkdir -p /volume2/docker/spt/spt-server
cd /volume2/docker/spt
vim compose.yml
docker compose up -d
```
