### ISSUE TITLE
Could you please create a 3.9.8 release? 

### ISSUE THREAD

**Issue by SrLicht** [AirryCo/spt-server-ci#2]
You would make it much easier for me to use the stable version in a Pterodactyl egg, at the moment I have to build the version myself using scripts and it takes too long.

**Comment by AirryCo** [comment]
The 3.9 version is only available as a Docker image. Of course, if you still need the Linux package for version 3.9.8, I can recompile it later.

```shell
docker pull stblog/spt-server:3.9.8
```

**Comment by SrLicht** [comment]
> The 3.9 version is only available as a Docker image. Of course, if you still need the Linux package for version 3.9.8, I can recompile it later.
> 
> ```shell
> docker pull stblog/spt-server:3.9.8
> ```

And unfortunately I only have access to Pterodactyl, I am not allowed to use docker.
I am using the egg from https://gist.github.com/superdarki/f07c45418a19ce62e5f2959c86ebb258 
which what it does is to download SPT from dev.sp-tarkov.com and then its dependencies (which think in total about 10gb) and then compile it to get the file from server

I would really appreciate it if you could recompile 3.9.8, it would save me a lot of time. It is much easier to simply download approx 200mb via github than to download 10 gb and then compile it.

**Comment by AirryCo** [comment]
https://github.com/AirryCo/spt-server-ci/releases/tag/3.9.8
